[build]
  command = "npm install && npx expo export --platform web"
  publish = "dist"
  base = "gentsconcerts-app"

[context.production.environment]
  EXPO_PUBLIC_API_URL = "https://gentsconcerts-api.onrender.com/api"

[context.deploy-preview.environment]
  EXPO_PUBLIC_API_URL = "https://gentsconcerts-api.onrender.com/api"
